### ISSUE TITLE
Cannot run the Makefile

### ISSUE THREAD

**Issue by cpluz-shrijayan** [bitcraze/crazyflie-simulation#28]
src/modules/src/power_distribution_quadrotor.c:33:10: fatal error: autoconf.h: No such file or directory
   33 | #include "autoconf.h"
      |          ^~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [Makefile:215: bindings_python] Error 1

![Screenshot from 2022-07-12 22-53-12](https://user-images.githubusercontent.com/81805145/178554857-298d8f9b-8f39-44b4-b270-ea60621b57a1.png)
![Screenshot from 2022-07-12 22-53-33](https://user-images.githubusercontent.com/81805145/178554866-f9ea8bb1-9355-46ba-8975-e01f31c44dd6.png)

**Comment by knmcguire** [comment]
This seems to be an issue in the firmware repo rather than the simulation repo: https://github.com/bitcraze/crazyflie-firmware

Are you sure that you have updated the firmware repo to the latest master branch?

Anyway, if the problem still persist, please ask a question about it on https://discussions.bitcraze.io/ instead
